name: rna-clock
channels:
  - conda-forge
  - BjornFJohansson
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
  - scanpy
  - click
  - lightgbm
  - plotly
  - jupyter-dash
  - pyarrow
  - pip
  - pip:
      - pycomfort
      - polars
      - lassonet