name: rna-clock
channels:
  - conda-forge
  - BjornFJohansson
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
  - scanpy
  - click
  - lightgbm
  - plotly
  - pyarrow
  - datamash>=1.8
  - dvc
  - dvc-gdrive
  - shap
  - mlflow
  -
  - pip
  - pip:
      - pycomfort
      - polars
      - lassonet